rolling-scopes-school/RSS-Teams-FE

- .firebaserc
- .github/workflows/deploy-client.yml
- .gitignore
- firebase.json
- package.json
> feat(#RSSFE-02): add firebase and github action configs

- src/components/Header/index.tsx
> RSSFE-03 fix: delete unused type

- src/components/Header/components/MenuWrapper/components/CoursesSelect/index.tsx
- src/components/Header/components/MenuWrapper/components/CoursesSelect/styled.ts
- src/components/Header/components/MenuWrapper/components/Nav/index.tsx
- src/components/Header/components/MenuWrapper/components/Nav/styled.ts
- src/components/Header/components/MenuWrapper/index.tsx
- src/components/Header/components/MenuWrapper/styled.ts
- src/components/Header/styled.ts
- src/typography/index.ts
Close #21 
Added adaptive for Header component
> RSSFE-10 Header adaptive

- src/modules/TeamsList/components/Teams/components/TeamUserTable/index.tsx
- src/modules/TeamsList/components/Teams/index.tsx
Поправил key props. Сделал их уникальными и не изменяемыми в рамках списков.
> RSSFE-09 - fix keys props (Teams page)

- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/components/MyTeamInfoLine/index.tsx
- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/components/MyTeamInfoLine/styled.tsx
Сделал анимационную визуализацию копирования пароля и ссылки на группу в MyTeam.
Теперь при копировании появляется затухающая подсветка, которая показывает, что совершено какое это действие. Надеюсь, из иконки самой кнопки понятно, какое это действие.
https://www.loom.com/share/e1d0743ad2e149dea0c5f70915598225
> refactor: add effect on copy to clipboard button

- src/modules/StudentsTable/components/Dashboard/components/TableBody/components/TableRow/index.tsx
Close #44 
Fixed popup appearing
> RSSFE-14 fix: fix popup

- src/modules/EditProfile/index.tsx
Добавил сохранение пользовательских данных при первой регистрации. И последующих тоже собственно.
> RSSFE-15: fix: save userData in store after registration 

- src/assets/svg/check.svg
- src/components/CourseField/index.tsx
- src/components/CourseField/styled.ts
- src/modules/EditProfile/components/UserCourseListItem/index.tsx
- src/modules/EditProfile/components/UserCourseListItem/styled.ts
- src/modules/EditProfile/index.tsx
- src/modules/EditProfile/styled.ts
- src/types.ts
> RSSFE-17 select editProfile

- src/modules/TeamsList/components/Teams/components/MemberListToggle/index.tsx
- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/components/MyTeamInfoLine/styled.tsx
- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/components/NotificationPopup/index.tsx
- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/components/NotificationPopup/styled.ts
- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/index.tsx
- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/styled.ts
Closes: #68 
Сделал выделение только текста при копировании
Сделал  мемберов 
Маленький попап с нотификацией при наведении. Настя пока не ответила, поэтому этот вариант попапа чисто моё видение. Если что, потом переделаю.
Лоадер скрин пока не обсуждали.
> RSSFE 21 UI fixes

- src/components/InputField/styled.ts
- src/modules/EditProfile/index.tsx
- src/modules/EditProfile/styled.ts
I brought the layout in accordance with the design layout
> RSSFE 20 layout of the profile form

- src/modules/TeamsList/components/Teams/components/MemberListToggle/index.tsx
- src/modules/TeamsList/components/Teams/components/MemberListToggle/styled.ts
> RSSFE-24 fix: return members arrows

- src/modules/EditProfile/index.tsx
- src/modules/EditProfile/styled.ts
Скрываю селект, когда больше нет курсов в списке
> RSSFE-26 hide select courses

- src/appConstants/index.ts
- src/components/App/index.tsx
- src/components/Header/components/MenuWrapper/components/CoursesSelect/index.tsx
- src/hooks/graphql/mutations/useCreateTeamMutation.ts
- src/hooks/graphql/mutations/useRemoveUserFromTeamMutation.ts
- src/modules/EditProfile/index.tsx
- src/modules/StudentsTable/components/Dashboard/components/TableBody/index.tsx
- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/index.tsx
- src/modules/TeamsList/index.tsx
- src/types.ts
Close #76
Added current course to local storage
Fixed pagination, updating cache after mutations
> RSSFE-25 fix: fix bugs

- src/modules/EditProfile/styled.ts
fix profile form position,
but size & position of cancel button  are by design
> RSSFE-28 fix form markup

- src/components/Loader/index.tsx
- src/components/Loader/styled.ts
- src/modules/TeamsList/components/Teams/components/MyTeam/components/MyTeamInfoBlock/components/NotificationPopup/styled.ts
> RSSFE-21 loader, notification

- src/graphql/queries/coursesQuery.ts
- src/graphql/queries/teamsQuery.ts
- src/graphql/queries/usersQuery.ts
- src/graphql/queries/whoAmIQuery.ts
- src/hooks/graphql/mutations/useCreateTeamMutation.ts
- src/hooks/graphql/mutations/useExpelUserFromTeamMutation.ts
- src/hooks/graphql/mutations/useRemoveUserFromTeamMutation.ts
Removed unused params from queries
> RSSFE-32 refactor: remove unused params from queries

- src/modules/EditProfile/formFields.ts
Поправил лимиты на длину строки,
Добавил допустимых символов в дискорд 
Добавил пробелы и тире к городам и странам
> RSSFE-31 correct input validation

- src/components/ModalCreateEditTeam/index.tsx
- src/modules/TeamsList/components/TeamListModals/index.tsx
Close #101 
Fixed closing modal
> RSSFE-33 fix: fix closing modal

- src/modules/EditProfile/formFields.ts
Close #102 
Allowed _ in telegram field
>  RSSFE-34 allow _

- src/components/App/index.tsx
- src/components/Header/components/MenuWrapper/components/Nav/index.tsx
Close #109 
Made dashoard link visible only for admins
> RSSFE-36 fix: fix dashboard appearing

- src/appConstants/index.ts
- src/components/App/index.tsx
- src/components/ModalCreateEditTeam/index.tsx
> RSSFE-34 fix: fix regexp for links

- src/components/App/index.tsx
- src/components/App/styled.ts
- src/components/Header/styled.ts
- src/components/Loader/index.tsx
- src/components/Loader/styled.ts
- src/modules/EditProfile/styled.ts
- src/modules/LoginPage/styled.ts
- src/modules/StudentsTable/styled.ts
- src/modules/TeamsList/index.tsx
- src/modules/TeamsList/styled.ts
Задал, что бы приложение занимало весь экран. Что бы форма профиля автоматом центрировалась на экран
> RSSFE 30 layour

- src/graphql/mutations/addUserToTeamMutation.ts
- src/graphql/mutations/updUserMutation.ts
Close #113 
Fixed appearing of user team data after user updating
> RSSFE-37 fix: fix appearing of user team data after user updating

- src/components/App/index.tsx
- src/components/Header/components/MenuWrapper/components/Nav/index.tsx
> RSSFE-40 feat: open dashboard

- src/graphql/mutations/index.ts
- src/graphql/mutations/sortStudentsMutation.ts
- src/hooks/graphql/index.ts
- src/hooks/graphql/mutations/useSortStudentsMutation.ts
- src/modules/TeamsList/components/Teams/index.tsx
- src/modules/TeamsList/index.tsx
- src/modules/TeamsList/styled.ts
Added sortStudents mutation
Added admin button for sorting students
Close #48
> RSSFE-16 sort students

- src/appConstants/index.ts
- src/components/App/index.tsx
- src/components/Footer/components/FooterContent/index.tsx
- src/components/Footer/components/LangSelect/index.tsx
- src/modules/LoginPage/loginPageReducer.ts
- src/translation/resources.ts
- src/types.ts
Added target="_blank" to links
Added new contants
Close #140
> RSFFE-43 fix: add another constants / attributes to links

- src/appConstants/index.ts
- src/components/App/styled.ts
- src/components/Footer/index.tsx
- src/components/Footer/styled.ts
- src/components/Header/components/MenuWrapper/components/CoursesSelect/styled.ts
- src/components/Header/styled.ts
- src/components/Loader/index.tsx
- src/components/Loader/styled.ts
- src/hooks/graphql/mutations/useRemoveUserFromCourseMutation.ts
- src/modules/EditProfile/components/UserCourseListItem/index.tsx
- src/modules/EditProfile/index.tsx
- src/modules/EditProfile/styled.ts
- src/modules/LoginPage/loginPageReducer.ts
- src/modules/LoginPage/selectors.ts
- src/modules/LoginPage/styled.ts
- src/modules/StudentsTable/styled.ts
- src/modules/TeamsList/index.tsx
- src/modules/TeamsList/styled.ts
- src/types.ts
- src/typography/index.ts
Fixed footer + editProfile styles
> RSSFE-43 fix: fix styles

- package.json
- src/store/index.tsx
Close #163 
Fixed Redux DevTools visibility on dev mode & added new scripts for prettier and lint
> RSSFE-49 fix: fix redux devtools for dev mode & add new scripts

- src/appConstants/index.ts
- src/components/App/index.tsx
- src/components/ErrorBoundary/index.tsx
- src/components/ErrorBoundary/styled.ts
- src/components/ErrorModal/index.tsx
- src/components/ModalEditCourse/index.tsx
- src/index.tsx
- src/modules/AdminPage/components/ContentWrapper/components/AddCourseBlock/index.tsx
- src/modules/AdminPage/components/ContentWrapper/components/CoursesList/index.tsx
- src/modules/AdminPage/components/ContentWrapper/index.tsx
- src/modules/EditProfile/index.tsx
- src/modules/StudentsTable/index.tsx
- src/modules/TeamsList/components/TeamListModals/useCommonMutations.ts
- src/modules/TeamsList/index.tsx
> RSSFE-51: fix dead token

- src/appConstants/index.ts
- src/components/FilterForm/filterFormFields.ts
- src/components/FilterForm/index.tsx
- src/components/FilterForm/styled.ts
- src/components/FilterSelect/index.tsx
- src/components/FilterSelect/styled.ts
- src/components/TablePopup/styled.ts
- src/modules/EditProfile/styled.ts
- src/modules/StudentsTable/components/Dashboard/components/TableBody/components/TableRow/components/TableItem/index.tsx
- src/modules/StudentsTable/components/Dashboard/components/TableBody/index.tsx
- src/modules/StudentsTable/components/Dashboard/components/TableBody/styles.css
- src/modules/StudentsTable/components/Dashboard/styled.ts
- src/modules/StudentsTable/index.tsx
- src/translation/en/en.json
- src/translation/ru/ru.json
- src/types.ts
Added Role column to Dashboard
Added filter by role
> RSSFE-50-1

- src/appConstants/index.ts
- src/translation/en/en.json
- src/translation/ru/ru.json
> RSSFE-56: Added previous year to new course name validation
